package jenkins;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
        System.out.println();
        System.out.println("WebHooks Integrated");
        System.out.println("Jenkins Test");
        System.out.println();
    }
}
